### ISSUE TITLE
App ELB information in webhook payloads

### ISSUE THREAD

**Issue by anthonyrisinger** [convox/rack#201] opened 2015-12-07 15:55 UTC
I'm developing a small webservice to receive `app:create` and `app:delete` events and provision a CNAME pointing back to the ELB associated with the newly minted app. Would it be possible to include this information in the POST payload? I can probably do the legwork of adding this feature as it would prevent me from needing to call back into the convox api, or even need the ability to do so (could be one-way only at that point)

**Comment by csquared** [comment] 2015-12-16 00:16
Great call and use case. I know of someone else using webhooks to do something similar and think that passing this info along would make everyone's life easier. If you wanna take a crack at this lemme know if i can do anything to help.

Also, @nzoschke is working on sending a web hook when the deploy has completed (which might be the better time to cut over DNS) in this PR https://github.com/convox/rack/pull/216 so maybe we can get them there?

**Comment by csquared** [comment] 2015-12-16 00:17
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;b9sPEUaa&#x2F;272-webhook-data"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> webhook data</a>

**Comment by xtfxme** [comment] 2015-12-16 04:26
Yes, after actually implementing this (and mentioned in Trello), I now know the balancers are not created until first promotion. I modified the service to react to `release:promote` and `app:delete` events, but since the webhook is eager, I end up receiving it sometime before the app (balancers) is ready to actually do useful work. Maybe we just need more events? Completion events? Something else?

Right now I have a thread that collects failed payloads and replays them 10 seconds later up to 3 times :-(

**Comment by MiguelMoll** [comment] 2017-03-29 13:12
Wondering if this is still an issue. Rack version `20170209003424` introduced changes to how build and release events in the form of 
```
release:start
release:complete
```
Where complete is sent once the promotion is done. I'm going to close the issue for now but please feel free to open it again if the issue is still present.

**Closed by MiguelMoll** 2017-03-29 13:12 UTC
Labels: area/deploy, kind/feature
