### ISSUE TITLE
Deploying docker images with ENTRYPOINT fails

### ISSUE THREAD

**Issue by ddollar** [convox/rack#1010] opened 2016-08-09 16:51 UTC
Looks like we try to wrap everything in `sh -c` which fails on Docker images that have an `ENTRYPOINT` and no `CMD`

**Comment by leftdevel** [comment] 2016-09-12 19:02
Hi There. I just hit this issue. `convox start` treats the 'command' entry differently than `docker-compose`.

According to the docker-compose.yml spec, if a 'command' is supplied, then the value will be passed as an arg to the entrypoint. I'm printing the arguments in my entrypoint file (.sh). And I see that it comes pre-fixed with "sh -c" when I run it with convox.

Is there anyway to get around this? Thanks.

**Comment by tommikaikkonen** [comment] 2016-11-07 23:49
Hit this issue as well. It seems I can't pass kill signals to the application I'm working on for graceful shutdown as that would require setting a different `ENTRYPOINT`; `sh -c` doesn't pass signals.

Before the issue is fixed, any ideas for workarounds are appreciated!

**Comment by soulware** [comment] 2016-11-08 01:16
Looks like this may be related to - https://github.com/convox/rack/pull/449

**Comment by tommikaikkonen** [comment] 2016-11-08 01:52
I tried setting `command` in `docker-compose.yml` as an array (exec form) and it does get rid of the `sh -c`. I use `convox start worker <command>` for various other commands, where this does not work though; it uses the shell form for the command as opposed to the exec form.

I was able to make a hacky workaround by specifying an entrypoint script that removes the `sh -c` that Convox passes in.

**Closed** 2018-01-26 14:46 UTC
Labels: status/1-accepted
