### ISSUE TITLE
Negation in .dockerignore unsupported in `convox deploy`

### ISSUE THREAD

**Issue by kolanos** [convox/rack#2253] opened 2017-07-14 19:34 UTC
I have a `.dockerignore` with the following entries:

    .git
    !.git/logs/HEAD
    !.git/HEAD

Which Docker itself recognizes, but `convox deploy` doesn't include them in the tarball it creates. Tried including the `.git` line after the negation entries as well, but same result.

**Comment by ddollar** [comment] 2018-01-26 14:12
Closing as duplicate of #2303

**Closed by ddollar** 2018-01-26 14:12 UTC
