### ISSUE TITLE
Add ability to do `convox ps` for all apps in a rack

### ISSUE THREAD

**Issue by aisipos** [convox/rack#443] opened 2016-03-10 23:51 UTC
Sometimes when addressing issues relating to your entire rack it would be helpful to see all processes running in all apps in a rack. There is no current option for `convox ps` to do that, having one could be helpful.

**Comment by anthonyrisinger** [comment] 2016-03-10 23:57
Dupe of https://github.com/convox/rack/issues/272 methinks :-)

**Comment by nzoschke** [comment] 2016-03-28 20:12
This is a duplicate of https://github.com/convox/rack/issues/272. Closing in favor of that.

**Closed by nzoschke** 2016-03-28 20:12 UTC
