### ISSUE TITLE
return process ID from run api

### ISSUE THREAD

**Issue by contra** [convox/rack#2067] opened 2017-03-16 21:58 UTC
Right now, running a process just returns `{ "success": true }` which isn't very useful. If the API returned the process ID (at the very least) it would be a lot more useful. This is true for most other endpoints, but let's start with this one.

Our use case is programmatically executing a process w/ specified args, and then being able to kill it later if needed. If we don't know the process ID we can't check the status or kill it later.

**Comment by contra** [comment] 2017-03-16 22:14
Also, if the process failed to start (immediately died with an error) it would be nice if that was reflected immediately in the API, and would also be extremely useful for the CLI.

**Comment by contra** [comment] 2017-04-03 16:29
This should be pretty easy after looking through stuff:

Will require a one or two line change. The PID is available in the endpoint handler already as `_` https://github.com/convox/rack/blob/master/api/controllers/processes.go#L119

Just needs to be returned on L130 in the response. I could attempt a PR myself but I'm assuming you'll be able to do it much quicker than reviewing my shitty go code.

**Comment by ddollar** [comment] 2017-04-07 01:06
Duplicate of #1295

**Closed by ddollar** 2017-04-07 01:06 UTC
Labels: area/api, kind/feature
