### ISSUE TITLE
convox init should support native docker

### ISSUE THREAD

**Issue by kemmott** [convox/rack#644] opened 2016-05-17 05:35 UTC
I'd like to use convox locally with the beta native docker for Mac, and not have to use boot2docker via docker-machine.

**Comment by mattmanning** [comment] 2016-05-17 19:58
Hi @kemmott What kinds of problems are you seeing? I'm currently using Convox locally with Docker for Mac.

**Comment by kemmott** [comment] 2016-05-18 15:07
ah, maybe I misinterpreted the result - if I run docker-machine ls, I see my old default virtualbox in a stopped state, showing docker version as "unknown". So when I do a convox init, I get:

Initializing unknown
ERROR: Asset init/unknown/Dockerfile not found

**Comment by clekstro** [comment] 2016-05-21 19:46
I get the exact same error. Given that the files aren't generated, is there a workaround or something else I'm doing wrong?

**Comment by ddollar** [comment] 2016-05-21 20:07
Closing this one as a duplicate of #663 since there's a bit more info there.

**Closed by ddollar** 2016-05-21 20:07 UTC
Labels: needs info
