### ISSUE TITLE
invalid manifest: yaml: unmarshal errors

### ISSUE THREAD

**Issue by cappelaere** [convox/rack#313] opened 2016-01-30 23:49 UTC
```shell
web.BNPGOEZOWRI: digest: sha256:75b07c54db213db554d5da9ba202cb83e808850f57108a998c6f184208e1da27 size: 82368
Promoting RAPAHJTSKQV... ERROR: invalid manifest: yaml: unmarshal errors:
  line 6: cannot unmarshal !!map into []string
  line 16: cannot unmarshal !!map into []string

Thanks,
Pat.
[docker-compose.yml.txt](https://github.com/convox/rack/files/111051/docker-compose.yml.txt)

**Comment by nzoschke** [comment] 2016-02-09 20:18
Copying the contents of the docker-compose.yml here for reference:

```
web:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: 'cd /app/user && node server.js'
  expose: 
    - '3000'
  env_file:
    - ./docker.env
  environment:
    NODE_ENV: production
    PORT: 3000
    PATH: /app/user/.heroku/node/bin:$PATH
  ports:
    - '80:3000'

worker:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: bash
  expose: 
    - '3000'
  env_file:
    - ./docker.env
  environment:
    NODE_ENV: production
    PORT: 3000
    PATH: /app/user/.heroku/node/bin:$PATH
  ports:
    - '3000:3000'
```

**Comment by nzoschke** [comment] 2016-02-10 19:10
The error is occurring due to your manifest environment section. It looks like we currently are only parsing the environment correctly when it is an array of `k=v` strings.

To work around this you can change your docker-compose.yml to:

```yaml
web:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: 'cd /app/user && node server.js'
  expose: 
    - '3000'
  env_file:
    - ./docker.env
  environment:
    - NODE_ENV=production
    - PORT=3000
    - PATH=/app/user/.heroku/node/bin:$PATH
  ports:
    - '80:3000'

worker:
  build: .
  dockerfile: Dockerfile_production
  working_dir: /app/user
  command: bash
  expose: 
    - '3000'
  env_file:
    - ./docker.env
  environment:
    - NODE_ENV=production
    - PORT=3000
    - PATH=/app/user/.heroku/node/bin:$PATH
  ports:
    - '3000:3000'
```

**Comment by nzoschke** [comment] 2016-02-10 19:13
But it is a bug that docker compose and `convox start`support the other form, but `convox deploy` doesn't. `convox start` does better parsing here:

https://github.com/convox/rack/blob/master/api/manifest/manifest.go#L304

Where `convox deploy` does simple YAML unmarshaling here:

https://github.com/convox/rack/blob/master/api/models/manifest.go#L24

**Comment by nzoschke** [comment] 2016-02-10 19:14
Ah, this is a duplicate of https://github.com/convox/rack/issues/112. Closing this issue in favor of the earlier one.

**Closed by nzoschke** 2016-02-10 19:14 UTC
