### ISSUE TITLE
Shared Volumes

### ISSUE THREAD

**Issue by timmyzaid** [convox/rack#1317] opened 2016-10-18 15:13 UTC
I have multiple containers that need to access the same volume in order to allow each container to do individualized operations on that data. For instance, one to serve the files, one to write the files, one to aggregate the files, etc... These could be combined into a single container but I think that would invalidate the single responsibility principle and, additionally, some of the services require more resources than the others, so I would like to be able to deploy more instances of those. Ideally, this could be accomplished using the docker file keyword <code>volumes_from</code>.

**Comment by ddollar** [comment] 2017-01-04 19:38
Dupe of #1140

**Closed by ddollar** 2017-01-04 19:38 UTC
Labels: kind/feature
