### ISSUE TITLE
CLI often returns 500 error

### ISSUE THREAD

**Issue by ethanfrey** [convox/rack#511] opened 2016-04-05 13:36 UTC
In general, I can use the tools, and get good results while setting up a demo app.

One minor issue I have is that about 25% of the time the command print out:
`ERROR: response status: 500`

If I run them a second time 1-2 seconds later, they work.  In the end I get the data without much delay, buy it is a bit unsettling to see so many 500 errors.  Maybe there is a problem in the server that can be fixed, or maybe there is some infrastructure issue and the CLI can simply do one retry at every 500 to avoid showing the problem to the end user (hide it rather than fix it).

The main problem here is image, an if I try to make a presentation for the dev team with so many error code, it is hard to instill confidence...

**Comment by nzoschke** [comment] 2016-04-12 22:44
Thanks for your report. Can you copy and paste some commands and outputs that are producing errors and 500s?

In general we take the uptime and error rate of the API very seriously. I don't expect this behavior and would love to get more information to help root cause and make it a better experience for you.

**Comment by nzoschke** [comment] 2016-05-03 15:47
Closing this for lack of a reproducible case. I do appreciate the report, please feel free to re-open it if you continue to see 500s.

**Closed by nzoschke** 2016-05-03 15:47 UTC
