### ISSUE TITLE
convox start is ignore -f

### ISSUE THREAD

**Issue by patrickomeara** [convox/rack#923] opened 2016-07-26 03:25 UTC
I have updated to the latest cli and have since been hitting this issue

`convox start -f docker-compose-local.yml` doesn't seem to be taking the `-f` in
#### docker-compose-local.yml
```
web:
  build: .
  dockerfile: Dockerfile.local
  ports:
    - 80:80
```

#### Dockerfile.local
```
FROM fixd/web:base

ADD ./package.json /src/package.json
RUN  npm install
```
This builds using `Dockerfile` from `docker-compose.yml` instead of `Dockerfile.local` from `docker-compose-local.yml`

 ```
build  │ running: docker build -f ./Dockerfile -t convox-5f68f5f97b .
```
none of the directives in `Dockerfile.local` are ran, but it builds `Dockerfile` twice

```
Sending build context to Docker daemon 12.23 MB 557.1 kB
build  │ Step 1 : FROM php:7.0-apache
build  │  ---> 9b9179bebb98
build  │ Step 2 : MAINTAINER patrickomeara <redacted>
build  │  ---> Using cache
build  │  ---> bcc1c10804a7
build  │ Step 3 : ADD docker/web/scripts/docker-php-pecl-install /usr/local/bin/
build  │  ---> Using cache
build  │  ---> b90a9dc2fc2d
<truncated>
Sending build context to Docker daemon 12.23 MB 557.1 kB
build  │ Step 1 : FROM php:7.0-apache
build  │  ---> 9b9179bebb98
build  │ Step 2 : MAINTAINER patrickomeara <redacted>
build  │  ---> Using cache
build  │  ---> bcc1c10804a7
build  │ Step 3 : ADD docker/web/scripts/docker-php-pecl-install /usr/local/bin/
build  │  ---> Using cache
build  │  ---> b90a9dc2fc2d
```

**Comment by jordansexton** [comment] 2016-07-26 20:28
Probably duplicate of #903

**Comment by jordansexton** [comment] 2016-07-26 20:29
In short, it is taking the docker-compose.yml file, but it's ignoring the `dockerfile` directive.

**Closed** 2016-07-31 01:30 UTC
