### ISSUE TITLE
Convox should use mem_limit field in docker-compose.yml 

### ISSUE THREAD

**Issue by snario** [convox/rack#636] opened 2016-05-15 23:01 UTC
There is a field `mem_limit` in the Docker Compose manifest: https://docs.docker.com/compose/compose-file/#cpu-shares-cpu-quota-cpuset-domainname-hostname-ipc-mac-address-mem-limit-memswap-limit-privileged-read-only-restart-shm-size-stdin-open-tty-user-working-dir

Using it should scale the process automatically, e.g.,

```
app:
    mem_limit: 2048
```

same as

```
convox scale app --memory=2048
```

**Comment by ddollar** [comment] 2016-05-18 14:10
Dupe of #353

**Closed by ddollar** 2016-05-18 14:10 UTC
Labels: enhancement, help wanted
