### ISSUE TITLE
'convox instances ssh' hangs terminal

### ISSUE THREAD

**Issue by soulshake** [convox/rack#1441] opened 2016-12-06 15:41 UTC
## What I do

I try to SSH to an instance where a successful keyroll has not been performed:

```
$ convox instances ssh i-01b7e71d272f4eebc
ERROR: ssh: no key found
<terminal hangs forever>
```
## What I expect to happen

To get an interactive shell on one of my instances, or to receive an error message (key missing, etc) followed by an exit.

## What actually happens

The terminal freezes completely. `Ctrl-C`, `~.` don't work; I have to close the terminal window completely.

**Comment by soulshake** [comment] 2016-12-06 15:42
![](https://github.trello.services/images/mini-trello-icon.png) ['convox instances ssh' hangs terminal](https://trello.com/c/303pBb19/1328-convox-instances-ssh-hangs-terminal)

**Comment by ddollar** [comment] 2017-01-04 20:32
Dupe of #1328

**Closed by ddollar** 2017-01-04 20:32 UTC
Labels: kind/bug, status/1-accepted

**Comment by ernestom** [comment] 2017-01-24 01:16
I can still experience this with 20170123152656:

```
$ convox instances ssh i-033b3fdb71d32dba4
ERROR: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
<terminal hangs until I kill the convox process>
```

**Comment by honeserviceuser** [comment] 2017-02-02 04:03
Experiencing this as well
