### ISSUE TITLE
Code sync stops working [convox start]

### ISSUE THREAD

**Issue by soulshake** [convox/rack#1404] opened 2016-11-17 14:59 UTC
Every once in a while, changes made locally stop being copied to containers launched with `convox start`.

I haven't found a way to reliably reproduce this.

**Comment by soulshake** [comment] 2016-11-17 14:59
![](https://github.trello.services/images/mini-trello-icon.png) [Files Not Syncing to Containers](https://trello.com/c/Wlo38pGT/1181-files-not-syncing-to-containers)

**Comment by soulshake** [comment] 2016-11-17 15:00
![](https://github.trello.services/images/mini-trello-icon.png) [Code sync not working](https://trello.com/c/QgVgzdq4/1201-code-sync-not-working)

**Comment by mattmanning** [comment] 2016-11-21 15:40
![](https://github.trello.services/images/mini-trello-icon.png) [Files Not Syncing to Containers](https://trello.com/c/Wlo38pGT/1181-files-not-syncing-to-containers)

**Comment by bluemaex** [comment] 2016-12-22 18:02
I am constantly running in this issue too. The sync just stops working at some point. I sadly also have no reliable way how to reproduce this. But it happens at least once a day for me.

The only thing I found out so far is that if I have another filewatcher running like ``npm watch`` it decreases the time code sync reliably works for me. 

Is there a way how I can give you more infos or track this down?  I tried getting debiug informations with ``CONVOX_DEBUG=TRUE`` and ``DEBUG=true`` but there is no different behaviour for me.

```
❯ convox --version
client: 20161217043656
ERROR: must login first
```

**Comment by ddollar** [comment] 2016-12-22 18:22
Fixed by #1489

**Closed** 2017-01-04 19:21 UTC

**Comment by till** [comment] 2017-01-05 15:23
@ddollar this still seems to happen with the latest release. We can repro on Mac & Linux. It just doesn't work reliably at all.

**Comment by ddollar** [comment] 2017-01-05 15:31
Do you have a repo or repro steps that you can share? We've been throwing some pretty intense npm installs at it with no issues so far.

**Comment by till** [comment] 2017-01-05 15:54
@ddollar it's not even an npm install, it just stops working in the middle. It claims it syncs files, but it doesn't sync them.

**Comment by ernestom** [comment] 2017-01-07 03:04
My team and I have seen this behavior with the latest releases as well. No way to reproduce it though. Sometimes code changes are not picked, and sometimes they are but have no effect. I've seen this happening every two days.
