### ISSUE TITLE
YAML references in docker-compose.yml break in deployment.

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#481] opened 2016-03-25 22:10 UTC
I have a `docker-compose.yml` like this:

```
web:
  environment: &env
    - FOO=bar
    - BAZ=qux
worker:
  environment:
    << *env
```

This works with `convox start`, but when I `convox deploy` I get an error like:

```
Promoting RPFKWRAEKCF... ERROR: invalid manifest: yaml: unmarshal errors:
  line 4: cannot unmarshal !!str `<< *env` into []string
```

**Comment by nathany** [comment] 2016-04-19 01:20
It looks like references are a YAML 1.2 feature.

libcompose makes use of this library, which may support them:
https://github.com/cloudfoundry-incubator/candiedyaml

**Comment by nzoschke** [comment] 2016-04-22 01:08
I'm very much in favor of replacing our simple yaml parsing in favor libcompose. 

We've already had countless errors in parsing and supporting the numerous forms docker-compose supports. Sharing this responsibility with `docker/libcompose` seems like a good way to share the work here.

**Comment by nzoschke** [comment] 2016-04-22 01:10
That said, we are not aiming for 100% docker-compose compatibility. We do reserve the right to say that we don't support parts of its syntax. But even that requires a great parser so we can offer nice error messages, not `cannot unmarshal !!str`

**Comment by nzoschke** [comment] 2016-04-25 14:47
Here's a couple sketches for scope...

## Improve parsing only

There's plenty of existing logic build around the `api/manifest` and `api/models/manifest` Manifest and ManifestEntry structs. 

- [ ] Parse docker-compose with libcompose
- [ ] Copy resulting settings into existing rack/api/manifest Manifest and ManifestEntry structs for convox start and convox build
- [ ] Write some tests around various yaml -> libcompose -> Manifest / ManifestEntry parsing

Stretch goal

- [ ] Change `Command interface{}`, etc. on ManifestEntry to a canonical data type

**Comment by nathany** [comment] 2016-04-25 14:47
libcompose looks to be a lot more than the yaml parser. It's a complete replacement of the docker-compose CLI.

**Comment by nzoschke** [comment] 2016-04-25 14:55
## Manifest Refactor

As we work towards a 1.0 release, it's a great time to pay down some tech debt. The existing manifest stuff has some known problems:

* Parsing errors
* Bad testing strategy
* Poor test coverage
* Shells out to the Docker CLI where using the Docker Client is probably a better strategy
* Confusion between `api/manifest` and `api/models/manifest`

I started a spike around this on #536 but it hasn't gotten review nor is it executed quite right. Here is how I would continue that work:

- [ ] Review #536
- [ ] Design a provider interface and where it lives in the project
- [ ] Extract build, run, etc. logic from the Test Provider
- [ ] Port existing functionality into a DockerCLI provider

**Comment by nzoschke** [comment] 2016-04-25 15:02
@nathany yeah. In general you can think of `convox start` as a replacement of the docker-compose CLI too. 

Same goal: one command to start an application. Different flavor: convox is much more strict about what it accepts and more opinionated about the development runtime it orchestrates. 

These opinions make it possible for us to guarantee what's running locally will run well in the convox production environment.

Some key differences:

- Avoiding volume mounts in favor of simple file sync in development
- Avoiding overlay networks and ambassador containers for container linking in favor of 12 factor DATABASE_URL style environment variables 
- Custom labels like `convox.port.443.proxy=true` which start a dev utility as well as configure production settings

The goal is to make `convox start` a validation pass as well as starting your environment. If you do something in docker-compose.yml that isn't compatible with Convox, the tool should tell you why it doesn't work and how to fix it.

**Comment by awsmsrc** [comment] 2016-04-25 15:09
@nathany I was playing with libcompose a while ago. IMO it is definitely the way to go although there are some rough edges. This issue: https://github.com/docker/libcompose/issues/185 has some sample code in it to get you started (or you can educate me on why we shouldn't use it :) )

**Comment by nathany** [comment] 2016-04-25 15:15
This is a much more ambitious task than the original issue. :smile:

@mattmanning In the examples I've seen of merging maps they have a colon between << and *env. I'm going to check that out. Why it is different between start vs. deploy is a bit baffling to me atm.

```yaml
web:
  environment: &env
    - FOO=bar
    - BAZ=qux
worker:
  environment:
    << : *env
```

**Comment by awsmsrc** [comment] 2016-04-25 15:21
Hey @nathany you're totally right. We have seen numerous new issues pop up with regard to YAML parsing which is why we were thinking of moving this issue upstream. I still think we would like compose eventually but iI think the main thing here is to fix the issue in any way you like (the simpler the better) and add some tests that way when we move to libcompose it should be a lot easier with fewer chances of regressions

**Comment by nzoschke** [comment] 2016-04-25 15:25
Good call, there's an even simpler scope here:

## Clean up YAML Parsing

- [ ] Use the existing `gopkg.in/yaml.v2` parser
- [ ] Sort out known unmarshall errors like this environment reference
- [ ] Write tests around the unmarshall errors

Stretch goals

- [ ] Review and unify api/manifest vs api/models/manifest yaml parsing

**Comment by nathany** [comment] 2016-04-25 15:30
If that doesn't work, the candiedyaml parser that libcompose uses has the same Unmarshal API as gopkg.in/yaml.v2.
https://godoc.org/github.com/cloudfoundry-incubator/candiedyaml

Also, `api/provider/aws/builds.go` is unmarshalling yaml directly. It looks like it's using the manifest stuff, so maybe there is some room for a light refactoring.

**Comment by nzoschke** [comment] 2016-04-25 15:54
Another possible yaml parsing problem: https://github.com/convox/rack/issues/112

**Comment by nathany** [comment] 2016-04-25 17:49
The YAML in @mattmanning example is invalid.

Locally the doesn't have the environment variables but gives no error:

```
main   | docker run -i --name go-app-main -e BAZ=qux -e FOO=bar -p 80:5000 go-app/main sh -c go-wrapper run
worker | docker run -i --name go-app-worker go-app/worker sh -c go-wrapper run
```

During deploy it gives an error.

```
Promoting RSOETOCHZUR... ERROR: invalid manifest: yaml: unmarshal errors:
  line 12: cannot unmarshal !!str `<< *env` into []string
```

This little example works in both cases:

```
main:
  build: .
  ports:
    - 80:5000
  command: go-wrapper run
  environment: &env
    - FOO=bar
    - BAZ=qux
worker:
  build: .
  command: go-wrapper run
  environment:
    *env
```

**Closed** 2016-05-02 18:03 UTC
Labels: priority
