### ISSUE TITLE
Syslog unlinking / deleting not working

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1181] opened 2016-09-02 18:36 UTC
Looks like it might be naming-related. Note the extra dash at the end of `httpd` in the error message.

```
$ convox services unlink syslog-8986 -a httpd
ERROR: httpd- not found

$ convox services delete syslog-8986
Deleting syslog-8986... ERROR: httpd- not found
```

**Comment by mattmanning** [comment] 2016-09-02 18:40
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fWE8GquS&#x2F;648-syslog-unlinking-deleting-not-working"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Syslog unlinking &#x2F; deleting not working</a>

**Comment by frankleng** [comment] 2016-09-04 08:28
linking is also not working

**Comment by ddollar** [comment] 2016-09-04 23:17
Duplicate of #1167

**Closed by ddollar** 2016-09-04 23:17 UTC
Labels: bug, priority
