### ISSUE TITLE
Creating a private Rack in subnets that already exist

### ISSUE THREAD

**Issue by jkurz** [convox/rack#1378] opened 2016-11-08 16:11 UTC
So there is already the ability to create a rack in a VPC that already exists, but what if I wanted to go further and use subnets that already exist also? 

These subnets already have Network Gateways and are private
These subnets are already in multiple AZs
These already use up our internal IP space that we want to use

We have the networking piece worked out and do not need convox installing new subnets inside our VPC. Is this something on your roadmap?

**Comment by maartenvanderhoef** [comment] 2016-11-15 14:01
+1 we would like to use Terraform for our AWS administration. It would be a major plus if Convox could fit in an already existing network.

**Comment by ddollar** [comment] 2016-11-15 15:22
@jkurz Not on the immediate roadmap but we could work with you to build that

**Comment by mwarkentin** [comment] 2016-11-15 19:11
@maartenvanderhoef Not sure if this is helpful, but we're using a combination of convox / terraform as well. We used convox to launch the rack (which creates the VPC, subnets, etc.), and then we're layering various Terraform configs on top of that. It's working well for us so far for the last 6 months or so.

**Comment by maartenvanderhoef** [comment] 2016-11-16 09:42
hi @mwarkentin, I'm sure that's possible when I'm manually using the output of Convox as input for TF. However TF is mastering the whole network, the many other AWS components, some of them in the same VPC, preferably the same subnet, external service checks etc.. To me it would make sense if TF can define the network Convox is operating in, happy to see it's made an enhancement.

**Comment by ddollar** [comment] 2017-01-04 19:42
Dupe of #1079, closing in favor of that one

**Closed by ddollar** 2017-01-04 19:42 UTC
Labels: kind/feature
