### ISSUE TITLE
cron job from one app appears in `convox ps` for another

### ISSUE THREAD

**Issue by skwp** [convox/rack#848] opened 2016-07-06 22:08 UTC
I've seen this happen a number of times. 

` convox ps --app verbo-slack`
ID            NAME   RELEASE      STARTED       COMMAND
49357eab7708  hubot  RRMLBQBNDFS  4 days ago    /bin/sh -c '/opt/hubot/bin/run -a slack'
fd0a091b9b36  nginx  RXFBHPSRRPK  1 second ago  sh -c execute_daily_alerts

Here you can see the second `nginx` container which is based on a convox lambda cronjob appears in the process list. Using `convox releases` on this app confirms that the release shown there is not one of the app's releases.

**Comment by MiguelMoll** [comment] 2016-07-07 13:20
Thanks for the report! :+1: As this is a dupe of #494, I'm closing this in favor of the original report.

**Closed by MiguelMoll** 2016-07-07 13:20 UTC
