### ISSUE TITLE
Segfault on `convox racks` when not logged in

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#2045] opened 2017-03-10 17:14 UTC
One of our devs reported this error when running `convox racks`:

```
convox version
client 20170307001710
```

```
convox racks
ERROR: must log in first
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x147f90]

goroutine 1 [running]:
panic(0xa905c0, 0xc4200100a0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/convox/rack/client.(*Client).Request(0x0, 0xbff8db, 0x3, 0xc01a4f,
0x6, 0x0, 0x0, 0x9a0b80, 0x0, 0x0)
    /tmp/release.v8YnN/src/github.com/convox/rack/client/client.go:427 +0x80
github.com/convox/rack/client.(*Client).Get(0x0, 0xc01a4f, 0x6, 0x9817e0,
0xc4202d25e0, 0x0, 0x0)
    /tmp/release.v8YnN/src/github.com/convox/rack/client/client.go:46 +0xb1
github.com/convox/rack/client.(*Client).Racks(0x0, 0x0, 0xc4201e7750, 0x1,
0x1, 0xc420203dd6)
    /tmp/release.v8YnN/src/github.com/convox/rack/client/racks.go:21 +0x86
main.cmdRacks(0xc420191540, 0x0, 0xc420191540)
    /tmp/release.v8YnN/src/github.com/convox/rack/cmd/convox/racks.go:24 +0x78
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x9e39a0,
0xc8d530, 0xc420191540, 0xc42001b900, 0x0)
    /tmp/release.v8YnN/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/app.go:484
+0xd4
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xc01648,
0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /tmp/release.v8YnN/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/command.go:207
+0xb96
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42017b6c0,
0xc42000a220, 0x2, 0x2, 0x0, 0x0)
    /tmp/release.v8YnN/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/app.go:249
+0x812
main.main()
    /tmp/release.v8YnN/src/github.com/convox/rack/cmd/convox/main.go:48 +0xa8
```

**Comment by soulshake** [comment] 2017-03-10 17:16
Related/duplicate of https://github.com/convox/rack/issues/1408

**Comment by soulshake** [comment] 2017-03-10 17:25
![](https://github.trello.services/images/mini-trello-icon.png) [Rack segfault when not logged in](https://trello.com/c/PZXakHrK/2099-rack-segfault-when-not-logged-in)

**Comment by MiguelMoll** [comment] 2017-03-14 20:32
Closing in favor of #1408. Thanks @mwarkentin

**Closed by MiguelMoll** 2017-03-14 20:32 UTC
Labels: kind/bug
