### ISSUE TITLE
convox does note cleanup ECR repo when app is deleted

### ISSUE THREAD

**Issue by frankleng** [convox/rack#876] opened 2016-07-18 20:23 UTC

**Comment by nzoschke** [comment] 2016-07-18 21:03
Thanks for the report. I can confirm this behavior.

Convox uses a custom handler for ECR, and it looks like its trying to delete the repo, but something isn't working right. Perhaps because the repo has data in it?

https://github.com/convox/rack/blob/master/api/cmd/formation/handler/ecr.go#L62

**Comment by mwarkentin** [comment] 2016-07-18 21:41
@nzoschke Yeah, you need to set the [`force` boolean](https://github.com/aws/aws-sdk-go/blob/master/service/ecr/api.go#L1180) to delete a repository which contains images.

**Comment by ddollar** [comment] 2016-08-10 14:20
A fix for this just wend out

**Closed** 2018-01-26 14:43 UTC
