### ISSUE TITLE
Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by matthewford** [convox/rack#1429] opened 2016-12-01 18:28 UTC
It would be nice to be able to manage ES via convox.

https://aws.amazon.com/elasticsearch-service/

**Comment by matthewford** [comment] 2016-12-01 18:31
previously mentioned: https://github.com/convox/rack/issues/377

**Comment by ddollar** [comment] 2017-01-04 19:27
Dupe of #1324

**Closed by ddollar** 2017-01-04 19:27 UTC
Labels: kind/feature
