### ISSUE TITLE
Amazon EC2 Container Registry (ECR)

### ISSUE THREAD

**Issue by nathany** [convox/rack#211] opened 2015-12-14 07:27 UTC
Are there plans to replace the [custom registry](https://github.com/convox/registry) with [ECR](https://aws.amazon.com/ecr/)? And importantly, how would you transition existing users?

I'm mostly interested in this [to reduce cost](https://github.com/convox/convox.github.io/issues/78) by having more resources available to my applications.

Though it could also reduce some complexity for Convox. Integration vs. invention.

**Comment by csquared** [comment] 2015-12-16 00:26
Absolutely in our plans and for the reasons mentioned :)

**Comment by alex** [comment] 2015-12-21 22:59
It's out now https://aws.amazon.com/about-aws/whats-new/2015/12/amazon-ec2-container-registry-now-availlable/ :-)

**Comment by nathany** [comment] 2015-12-22 06:02
Got a 404 from that link. Try this one: https://aws.amazon.com/blogs/aws/ec2-container-registry-now-generally-available/ linked from http://thenewstack.io/amazons-ec2-container-registry-goes-live/

**Comment by nzoschke** [comment] 2016-01-19 01:51
This is being worked on. Next steps are rebasing, testing and merging this PR

https://github.com/convox/rack/pull/249

**Comment by nathany** [comment] 2016-01-21 02:17
Looks like it's merged now.

**Comment by nzoschke** [comment] 2016-01-21 16:40
It is! `convox rack update` to get the changes.

You need to do 2 deploys to an app to get ECR. The first deploy creates the ECR Repository. The next deploy will start pushing images to that instead of the v1 registry.

**Comment by ha333823** [comment] 2016-01-21 17:14
Sorry, is this not backward compatible? getting error while creating convo app with latest version but in Oregon region which doesn't support ECR yet.

**Comment by nzoschke** [comment] 2016-01-21 18:45
Shoot, I only tested in us-east, so thank you for the report. It is intended to be backwards compatible.

I now see this bit of info:

> Effective today, Amazon ECR is available in US East (Northern Virginia) with more regions on the way soon!

For a short term fix you can update your rack back to a version before ECR.

The v1 registry is still running in your rack. I can change CloudFormation to not provision ECR if the region is not us-east-1 until ECR is available in more regions.

**Comment by nzoschke** [comment] 2016-01-21 19:10
Confirmed app creation is broken in eu-west-1

11:09:39 UTC-0800	CREATE_FAILED	Custom::ECRRepository	RegistryRepository	Invalid PhysicalResourceId
Physical ID:httpd2-RegistryRepository-1AS6DIMGBU8P4

**Comment by nzoschke** [comment] 2016-01-26 00:05
This was fixed in https://github.com/convox/rack/pull/274

**Closed by nzoschke** 2016-01-26 00:05 UTC
Labels: enhancement
