### ISSUE TITLE
`convox ps --stats` broken

### ISSUE THREAD

**Issue by spencerhakim** [convox/rack#2263] opened 2017-07-21 04:42 UTC
CPU and MEM consistently read as 0. Sample output:

```
$> convox ps --stats
ID            NAME   RELEASE      CPU %  MEM           MEM %  STARTED        COMMAND
77f83adfde04  web    RVYVWSOKJRB  0.00%  0.0MB/256MB   0.00%  8 minutes ago
```

**Comment by mwisner** [comment] 2017-07-22 15:02
Was just coming here to report this as well...

```
ID            NAME          RELEASE      CPU %  MEM          MEM %  STARTED         COMMAND
94dc14720cd6  celerybeat    RXJWKUWONDE  0.00%  0.0MB/256MB  0.00%  18 hours ago    celery -A mcs.tasks beat --workdir=/app -l INFO
474a12d8dc52  celeryworker  RXJWKUWONDE  0.00%  0.0MB/256MB  0.00%  12 hours ago    celery -A mcs.tasks worker --workdir=/app --concurrency=4 --without-gossip -l INFO
5d6a572f720c  celeryworker  RXJWKUWONDE  0.00%  0.0MB/256MB  0.00%  19 hours ago    celery -A mcs.tasks worker --workdir=/app --concurrency=4 --without-gossip -l INFO
5ea9ce555584  celeryworker  RXJWKUWONDE  0.00%  0.0MB/256MB  0.00%  19 hours ago    celery -A mcs.tasks worker --workdir=/app --concurrency=4 --without-gossip -l INFO
```

``` convox --version
client: 20170712221054
server: 20170712160322 (console.convox.com)
```

**Comment by mwarkentin** [comment] 2017-08-02 20:18
We're seeing this as well:

```
(keller)michaelwarkentin@mwarkentin juno-local (master) ~wave-dev/scylla~ $ convox ps --stats --app pronetwork
ID            NAME              RELEASE      CPU %  MEM           MEM %  STARTED         COMMAND
c97841d286a1  rpc               RUOCPTVIFSA  0.00%  0.0MB/256MB   0.00%  2 hours ago     sh -c /app/bin/rpc
97e7c3c91fda  web               RUOCPTVIFSA  0.00%  0.0MB/2560MB  0.00%  50 minutes ago  sh -c /app/bin/web
c447fbede821  web               RUOCPTVIFSA  0.00%  0.0MB/2560MB  0.00%  2 hours ago     sh -c /app/bin/web
d138e087bfb9  workermessagebus  RUOCPTVIFSA  0.00%  0.0MB/256MB   0.00%  2 hours ago     sh -c /app/bin/worker-messagebus
(keller)michaelwarkentin@mwarkentin juno-local (master) ~wave-dev/scylla~ $ convox -v
client: 20170727193936
server: 20170726204318 (convox.prod.wavehq.net)
```

**Comment by mwisner** [comment] 2017-09-19 12:53
Maybe I just need to look harder in the AWS UI but I can't seem to find this particular set of information anywhere... Does anyone know of an alternative location I see a cpu/mem usage per container?

Historical information would actually be pretty useful as well...

**Comment by ddollar** [comment] 2018-03-28 21:03
Dupe of #2485

**Closed by ddollar** 2018-03-28 21:03 UTC
Labels: kind/bug
