### ISSUE TITLE
env var overwrite for services with same build path

### ISSUE THREAD

**Issue by frsechet** [convox/rack#2886] opened 2018-08-28 06:33 UTC
The following convox.yml will result in the `q-train` service having `QUEUE_NAME=delete` as an environment variable in the ECS task definition. I'm guessing it has to do with having two services using the same build path, and convox using the environment variables from the second one.

```
services:
  q-train:
    build: ./resources/queues
    environment:
      - QUEUE_NAME=train

  q-delete:
    build: ./resources/queues
    environment:
      - QUEUE_NAME=delete
```

**Comment by ddollar** [comment] 2018-08-28 12:55
Unable to reproduce. For these kinds of issues please provide a sample repository that demonstrates the issue and include a transcript like this one.

```
$ cat convox.yml
services:
  web:
    build: .
    environment:
      - FOO=bar
      - VAR_ONE=0.5
      - VAR_TWO=0.17
      - VAR_THREE=0.11
      - VAR_FOUR=1
    port: 80
  web2:
    build: .
    environment:
      - FOO=baz
    port: 80

$ convox deploy
...

$ convox ps -a httpd2a
ID            SERVICE  STATUS   RELEASE      STARTED        COMMAND
6890917654ac  web      running  RRLAGKNKQOF  3 minutes ago
96bfc0a08173  web2     running  RRLAGKNKQOF  4 minutes ago

$ convox exec 6890917654ac "export | grep 'export FOO'" -a httpd2a
export FOO='bar'

$ convox exec 96bfc0a08173 "export | grep 'export FOO'" -a httpd2a
export FOO='baz'

$ convox run web "export | grep 'export FOO'" -a httpd2a
export FOO='bar'

$ convox run web2 "export | grep 'export FOO'" -a httpd2a
export FOO='baz'
```

**Comment by frsechet** [comment] 2018-08-29 06:43
Below a complete playbook. Anonymized repo to test is [here](https://github.com/frsechet/convox-overwrite-env-var) (it doesn't "work" as all containers are replaced with simple nginx but that's not the point here).

```
{8:25}~/spoc/convox/clevy-api-staging2 ➭ cx version
client: 20180828070853
server: 20180828070853 (xxxx)
{8:25}~/spoc/convox/clevy-api-staging2 ➭ cx apps create
Creating clevy-api-staging2... OK
{8:25}~/spoc/convox/clevy-api-staging2 ➭ cat env-init | cx env set --promote
Setting API_DOMAIN, API_URL, APP_URL, ASSETS_S3_BUCKET, ASSETS_URL, AWS_ACCESS_KEY_ID, AWS_ACCOUNT_ID, AWS_REGION, AWS_SECRET_ACCESS_KEY, CALLR_SECRET, CLEVY_NOTIFY_EMAIL, CLOUDFRONT_KEYPAIR_ID, CLOUDFRONT_PRIVATE_KEY, CRYPTR_SECRET, DB_DATABASE, DB_HOST, DB_PASSWORD, DB_USER, DEBUG, ELASTICSEARCH_HOST, ELASTICSEARCH_PORT, ITC_URL, ITC_WORKPLACE_ACCESS_TOKEN, JWT_SECRET, NPM_TOKEN, REDIS_HOST, S3_ASSETS_BUCKET, SERVICE_SECRET, STAGE, URL_SHORTENER_S3_BUCKET, URL_SHORTENER_URL, VECTORIZER_DOMAIN, WEBAPP_URL, WEBSOCKETS_DOMAIN, WEBSOCKETS_URL, WORKPLACE_VERIFY_TOKEN... OK
Release: RHYSOLKPFZT
Promoting RHYSOLKPFZT... cx OK
{8:26}~/spoc/convox/clevy-api-staging2 ➭ cx deploy
Packaging source... OK
... building stuff ...
Promoting RHMVRFJCGWU... OK
{8:27}~/spoc/convox/clevy-api-staging2 ➭ cx ps
ID            SERVICE          STATUS   RELEASE      STARTED         COMMAND
073c781940f9  main             running  RHMVRFJCGWU  3 seconds ago
b5a30e5ac6ab  main             running  RHMVRFJCGWU  4 seconds ago
f7177e69e255  main             running  RHMVRFJCGWU  5 seconds ago
4a3c08a34999  nlpapi           running  RHMVRFJCGWU  55 seconds ago
ad415b3c763f  nlpapi           running  RHMVRFJCGWU  55 seconds ago
e7a92fd3114a  nlpapi           running  RHMVRFJCGWU  55 seconds ago
2b987f1cce60  q-delete-intent  running  RHMVRFJCGWU  2 minutes ago
5299f70b03cd  q-train-intent   running  RHMVRFJCGWU  2 minutes ago
9e1dd4d88ae1  q-train-intent   running  RHMVRFJCGWU  2 minutes ago
ed1580d767f5  q-train-intent   running  RHMVRFJCGWU  2 minutes ago
519512bf5db5  websockets       running  RHMVRFJCGWU  30 seconds ago
6f933cddbdad  websockets       running  RHMVRFJCGWU  31 seconds ago
b19eabb030c8  websockets       running  RHMVRFJCGWU  30 seconds ago
{8:30}~/spoc/convox/clevy-api-staging2 ➭ cx exec 5299f70b03 env | sort <=== q-train-intent container

API_URL=https://api-staging.clevy.io
APP=clevy-api-staging2
AWS_ACCESS_KEY_ID=XXXXXXXXX
AWS_ACCOUNT_ID=XXXXXXXX
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/credentials/1ed2dc21-22fa-4529-81fe-ff05f71fbc92
AWS_REGION=eu-west-3
AWS_SECRET_ACCESS_KEY=xxxxxxxxx
BLUEBIRD_W_FORGOTTEN_RETURN=0
BUGSNAG_API_KEY=something
BUILD=BEIRESTRSXZ
BUILD_DESCRIPTION=
CONVOX_ENV_KEY=arn:aws:kms:eu-west-3:973267943737:key/e3e7c864-06fa-471c-bafd-3311eb6e305d
CONVOX_ENV_URL=s3://clevy-dev-clevy-api-staging2-settings-ujscsypl5riv/releases/RHMVRFJCGWU/env
CONVOX_ENV_VARS=API_URL,AWS_ACCESS_KEY_ID,AWS_ACCOUNT_ID,AWS_REGION,AWS_SECRET_ACCESS_KEY,BLUEBIRD_W_FORGOTTEN_RETURN,BUGSNAG_API_KEY,DEBUG,ELASTICSEARCH_HOST,ELASTICSEARCH_INDEX,ELASTICSEARCH_INDEX_PREFIX,ELASTICSEARCH_PORT,ELASTICSEARCH_REGION,NODE_ENV,NPM_TOKEN,QUEUE_NAME,REDIS_HOST,REDIS_PORT,SERVICE_SECRET,SQS_AWS_ACCOUNT_ID,SQS_ENDPOINT,SQS_QUEUE_PREFIX,SQS_REGION,STAGE
DEBUG=clevy:*
ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/d5c10b66-d215-4ffd-b6bb-b740ecc44f15/ecs-container-metadata.json
ELASTICSEARCH_HOST=xxxxxxxx
ELASTICSEARCH_INDEX=clevy:staging
ELASTICSEARCH_INDEX_PREFIX=clevy:staging
ELASTICSEARCH_PORT=443
ELASTICSEARCH_REGION=eu-west-3
HOME=/root
HOSTNAME=67de1455d5fe
MAIN_URL=https://clevy-api-staging2-main.clevy-Route-1FT7CTPJSHKEP-1127180389.eu-west-3.convox.site
NGINX_VERSION=1.15.2-1~stretch
NJS_VERSION=1.15.2.0.2.2-1~stretch
NODE_ENV=staging
NPM_TOKEN=xxxxxxxx
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
QUEUE_NAME=delete-intent   <======= should be train-intent (see env-init
RACK=clevy-dev
REDIS_HOST=xxxxxxxx
REDIS_PORT=6379
RELEASE=RHMVRFJCGWU
SERVICE_SECRET=xxxxxxxx
SQS_AWS_ACCOUNT_ID=XXXXXXXX
SQS_ENDPOINT=https://sqs.eu-west-3.amazonaws.com
SQS_QUEUE_PREFIX=clevy-staging
SQS_REGION=eu-west-3
STAGE=staging
TERM=xterm

**Comment by frsechet** [comment] 2018-08-29 06:45
Below a complete playbook. Anonymized repo to test is [here](https://github.com/frsechet/convox-overwrite-env-var) (it doesn't "work" as all containers are replaced with simple nginx but that's not the point here).

```
{8:25}~/spoc/convox/clevy-api-staging2 ➭ cx version
client: 20180828070853
server: 20180828070853 (xxxx)
{8:25}~/spoc/convox/clevy-api-staging2 ➭ cx apps create
Creating clevy-api-staging2... OK
{8:25}~/spoc/convox/clevy-api-staging2 ➭ cat env-init | cx env set --promote
Setting API_DOMAIN, API_URL, APP_URL, ASSETS_S3_BUCKET, ASSETS_URL, AWS_ACCESS_KEY_ID, AWS_ACCOUNT_ID, AWS_REGION, AWS_SECRET_ACCESS_KEY, CALLR_SECRET, CLEVY_NOTIFY_EMAIL, CLOUDFRONT_KEYPAIR_ID, CLOUDFRONT_PRIVATE_KEY, CRYPTR_SECRET, DB_DATABASE, DB_HOST, DB_PASSWORD, DB_USER, DEBUG, ELASTICSEARCH_HOST, ELASTICSEARCH_PORT, ITC_URL, ITC_WORKPLACE_ACCESS_TOKEN, JWT_SECRET, NPM_TOKEN, REDIS_HOST, S3_ASSETS_BUCKET, SERVICE_SECRET, STAGE, URL_SHORTENER_S3_BUCKET, URL_SHORTENER_URL, VECTORIZER_DOMAIN, WEBAPP_URL, WEBSOCKETS_DOMAIN, WEBSOCKETS_URL, WORKPLACE_VERIFY_TOKEN... OK
Release: RHYSOLKPFZT
Promoting RHYSOLKPFZT... cx OK
{8:26}~/spoc/convox/clevy-api-staging2 ➭ cx deploy
Packaging source... OK
... building stuff ...
Promoting RHMVRFJCGWU... OK
{8:27}~/spoc/convox/clevy-api-staging2 ➭ cx ps
ID            SERVICE          STATUS   RELEASE      STARTED         COMMAND
073c781940f9  main             running  RHMVRFJCGWU  3 seconds ago
b5a30e5ac6ab  main             running  RHMVRFJCGWU  4 seconds ago
f7177e69e255  main             running  RHMVRFJCGWU  5 seconds ago
4a3c08a34999  nlpapi           running  RHMVRFJCGWU  55 seconds ago
ad415b3c763f  nlpapi           running  RHMVRFJCGWU  55 seconds ago
e7a92fd3114a  nlpapi           running  RHMVRFJCGWU  55 seconds ago
2b987f1cce60  q-delete-intent  running  RHMVRFJCGWU  2 minutes ago
5299f70b03cd  q-train-intent   running  RHMVRFJCGWU  2 minutes ago
9e1dd4d88ae1  q-train-intent   running  RHMVRFJCGWU  2 minutes ago
ed1580d767f5  q-train-intent   running  RHMVRFJCGWU  2 minutes ago
519512bf5db5  websockets       running  RHMVRFJCGWU  30 seconds ago
6f933cddbdad  websockets       running  RHMVRFJCGWU  31 seconds ago
b19eabb030c8  websockets       running  RHMVRFJCGWU  30 seconds ago
{8:30}~/spoc/convox/clevy-api-staging2 ➭ cx exec 5299f70b03 env | sort <=== q-train-intent container

API_URL=https://api-staging.clevy.io
APP=clevy-api-staging2
AWS_ACCESS_KEY_ID=XXXXXXXXX
AWS_ACCOUNT_ID=XXXXXXXX
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=something
AWS_REGION=eu-west-3
AWS_SECRET_ACCESS_KEY=xxxxxxxxx
BLUEBIRD_W_FORGOTTEN_RETURN=0
BUGSNAG_API_KEY=something
BUILD=BEIRESTRSXZ
BUILD_DESCRIPTION=
CONVOX_ENV_KEY=something
CONVOX_ENV_URL=s3://xxxxxx
CONVOX_ENV_VARS=API_URL,AWS_ACCESS_KEY_ID,AWS_ACCOUNT_ID,AWS_REGION,AWS_SECRET_ACCESS_KEY,BLUEBIRD_W_FORGOTTEN_RETURN,BUGSNAG_API_KEY,DEBUG,ELASTICSEARCH_HOST,ELASTICSEARCH_INDEX,ELASTICSEARCH_INDEX_PREFIX,ELASTICSEARCH_PORT,ELASTICSEARCH_REGION,NODE_ENV,NPM_TOKEN,QUEUE_NAME,REDIS_HOST,REDIS_PORT,SERVICE_SECRET,SQS_AWS_ACCOUNT_ID,SQS_ENDPOINT,SQS_QUEUE_PREFIX,SQS_REGION,STAGE
DEBUG=clevy:*
ECS_CONTAINER_METADATA_FILE=/opt/ecs/metadata/d5c10b66-d215-4ffd-b6bb-b740ecc44f15/ecs-container-metadata.json
ELASTICSEARCH_HOST=xxxxxxxx
ELASTICSEARCH_INDEX=clevy:staging
ELASTICSEARCH_INDEX_PREFIX=clevy:staging
ELASTICSEARCH_PORT=443
ELASTICSEARCH_REGION=eu-west-3
HOME=/root
HOSTNAME=67de1455d5fe
MAIN_URL=some-url
NGINX_VERSION=1.15.2-1~stretch
NJS_VERSION=1.15.2.0.2.2-1~stretch
NODE_ENV=staging
NPM_TOKEN=xxxxxxxx
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
QUEUE_NAME=delete-intent   <======= should be train-intent (see env-init
RACK=clevy-dev
REDIS_HOST=xxxxxxxx
REDIS_PORT=6379
RELEASE=RHMVRFJCGWU
SERVICE_SECRET=xxxxxxxx
SQS_AWS_ACCOUNT_ID=XXXXXXXX
SQS_ENDPOINT=https://sqs.eu-west-3.amazonaws.com
SQS_QUEUE_PREFIX=clevy-staging
SQS_REGION=eu-west-3
STAGE=staging
TERM=xterm

**Comment by frsechet** [comment] 2018-09-29 07:13
Some more info this morning. I discovered that the right env vars are available during convox build, BUT the issue comes when the build is released. So either the release itself or the promote step goes wrong.

For example, if I change the convox.yml to something like that in one of the problematic services (`build` a custom dockerfile instead of `image`):
```
  q-train-intent:
    build:
      path: .
      manifest: ./Dockerfile-q-train-intent
    ...
```

And Dockerfile-q-train-intent has a combination of all the ARG and ENV I need, all the right environment variables are set inside the image.

However the variables injected into ECS are still wrong. I'm missing some, and some are completely wrong. Is there anything done to the env between when it's built and when it's released? A character that may cause issues down the road or something like that? How can I check the env variables that will be injected into the ECS task definition?

**Comment by ddollar** [comment] 2018-12-02 22:46
This was fixed via Console ticket

**Closed** 2018-12-02 22:46 UTC
Labels: kind/bug
