### ISSUE TITLE
App's scheduled-task not running in rack version 20160818013241

### ISSUE THREAD

**Issue by eladidan** [convox/rack#1093] opened 2016-08-19 02:26 UTC
After updating my rack today to version `20160818013241` (not sure what my previous version was. can’t seem to find the update in the rack logs), my scheduled task is not running. There’s no log for the app process having been queued (there is one for previous runs).

Looking at the scheduled-task’s lambda, the cloud-watch event invoked the lambda and it claims to have successfully ran (only it never made it to the rack)

from the lambda’s CW logs:
```
2016-08-18T22:00:08.694Z    <req-id>    REQUEST RECEIVED:
{
    "app": "my-app",
    "process": "my-process",
    "command": "python /path/to/scheduled/task"
}
2016-08-18T22:00:09.576Z    <req-id>    Status: 401 
2016-08-18T22:00:09.576Z    <req-id>    Headers:
{
    "www-authenticate": "Basic realm=\"Convox System\"",
    "date": "Thu, 18 Aug 2016 22:00:09 GMT",
    "content-length": "21",
    "content-type": "text/plain; charset=utf-8"
}
```

**Comment by soulware** [comment] 2016-08-19 17:59
Just saw this - think the issue #1097 I opened is actually a dupe of this.

**Comment by ddollar** [comment] 2016-08-19 21:08
Duped in #1097, tracking there.

**Closed by ddollar** 2016-08-19 21:08 UTC
