### ISSUE TITLE
Make ENTRYPOINT work with `convox run`

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#2014] opened 2017-03-07 04:37 UTC
From Slack:

"I’m noticing that when I convox run <process> env, I’m not seeing any environment variables that are set up by my ENTRYPOINT. This makes sense once I dig in, because I see that from Docker’s POV the command is just sleep (and then Convox docker execs in and starts a shell"

**Comment by dlanger** [comment] 2017-03-09 04:42
We define an `ENTRYPOINT` in our standard base image which does things like expand out `FOO_URL`-style envvars into `FOO_HOST`, `FOO_PORT`. 

These are necessary for us to run an app shell in a `convox run` container, so we've taken to doing `convox run web '/docker-entrypoint python manage.py shell_plus'`. Newer developers forget this, and while it works, it's a bit of a nasty thing to have to type out all the time.

**Comment by ddollar** [comment] 2017-04-07 01:22
Dupe of #1010

**Comment by mwarkentin** [comment] 2017-04-07 12:43
@ddollar Not directly - this issue is because of how convox turns `convox run <cmd>` into a `docker run sleep 3600 && docker exec <docker_id> <cmd>`. `docker run` uses the container `ENTRYPOINT`, `docker exec` doesn't.

Not sure if there's anything that can be done about that however (I'm not sure why the sleep + exec pattern is used, but I assume there's a reason :).

**Comment by mwarkentin** [comment] 2017-04-19 00:52
@ddollar Not sure if you saw my comment - can you confirm you think this is still a dupe of the other issue?

**Comment by ddollar** [comment] 2018-01-26 14:32
This works now

**Closed by ddollar** 2018-01-26 14:32 UTC
