### ISSUE TITLE
convox agent stops transmitting logs

### ISSUE THREAD

**Issue by ddollar** [convox/rack#520] opened 2016-04-06 21:23 UTC
don't have repro steps, but it appears convox/agent can hit a case where it stops transmitting logs

**Comment by nzoschke** [comment] 2016-04-12 22:10
There are lots of reports of this, so it's moved up to an urgent fix.

I suspect a root cause is how convox/agent is writing to Kinesis:

* Kinesis works best with the [Kinesis Producer Library](http://docs.aws.amazon.com//kinesis/latest/dev/developing-producers-with-kpl.html). The convox/agent go implementation is naive compared to this strategy
* The convox producer isn't doing much around throttling, rate limiting, and error handling. What could go wrong?
* convox/agent could have other concurrency bugs in container and log event handling
* convox/agent restarting has known problems with logs to kinesis

Cloudwatch Logs is also in the mix:

* The way convox/agent uses the cloudwatch logs driver is confusing, and always shows an intial error
* It doesn't emit additional telemetry about success or error rate

Docker logs API is in the mix:

* The logs API can lock up on its own
* It doesn't emit telemetry about log rate


My general plan of attack is:

* Add an alternative `convox logs` that talks directly to dockerd. This can be a temporary experiment and workaround for when Kinesis is failing, and a potential production path and way off of Kinesis
* Review convox/agent kinesis logging producer again. But I don't know anything obvious to try...
* Add more telemetry about container logs emitted, kinesis logs written and cloudwatch logs written. Get into CloudWatch metrics for a dashboard.

**Comment by nzoschke** [comment] 2016-04-28 20:34
This was fixed in https://github.com/convox/rack/releases/tag/20160425202355

**Closed by nzoschke** 2016-04-28 20:34 UTC
