### ISSUE TITLE
Autoscale triggers during application deployment

### ISSUE THREAD

**Issue by bladealslayer** [convox/rack#1250] opened 2016-09-22 06:56 UTC
I have a rack currently with 4 instances, autoscaling enabled. I have an app with desired scale 2 and deployment configuration allowing 50% minimum and 200% maximum running. During deployment, the rack autoscales +1 instance and then immediately autoscales down -1 instance as follows:

```
13:22:15 web:20160916121812/298cc4e1cdab ns=workers.autoscale at=autoscaleRack reason=width change=1
13:24:15 web:20160916121812/298cc4e1cdab ns=workers.autoscale at=autoscaleRack reason=memory change=-1
```

If I disable autoscaling, deployments manage to succeed, indicating that the rack has enough capacity. I suspect it would be tricky that autoscales takes into account app's deployment status and deployment settings (`convox.deployment.minimum` and `convox.deployment.maximum`), but if it's possible to avoid this kind of unnecessary scaling, it would be great!

Running rack release `20160916121812`.

**Comment by contra** [comment] 2016-09-23 22:00
Also having this issue on latest (

Not only does it trigger during deployment, it triggers on ANY change. Roll your API key to reproduce, watch autoscale freak out and take an insane amount of time to finish the change.

**Comment by ddollar** [comment] 2016-09-26 20:49
Currently all scheduled ECS services are taken into account when calculating the autoscaling width.

I'm not sure what is happening for you @contra but minor changes should not be triggering Autoscaling. If you submit a ticket in Console we can help dig in to your Rack.

**Comment by ddollar** [comment] 2016-09-26 20:58
I'm going to close this for now as working-as-intended. Autoscaling will bump instances up and down to grease the wheels for ECS. Please comment here if you're seeing any negative impact from the instance scaling.

**Closed by ddollar** 2016-09-26 20:58 UTC

**Comment by bladealslayer** [comment] 2016-09-27 07:14
@ddollar there seems to be an issue with timing:

I have a rack with `N` instances, autoscaling enabled.

1. `09:38:06` app's CF stack update starts (triggered by `convox deploy`)
2. `09:38:25
web:20160922164843/435a66f50d94 ns=workers.autoscale at=autoscaleRack reason=width change=1` - rack autoscales up to `N+1`
3. `09:39:15` - autoscaling group logs launching new instance
4. `09:40:24
web:20160922164843/435a66f50d94 ns=workers.autoscale at=autoscaleRack reason=memory change=-1` - rack autoscales down back to `N`
5. `09:40:43` - autoscaling group logs event terminating an instance
6. `09:41:21` - ECS agent on new instance (from step 3) logs that it has successfully registered with ECS.

So, there is a window in which the rack has `N-1` instances. While testing, I haven't noticed this causing a real problem yet.

Would it be possible for convox to wait for instance to register to ECS before considering the rack update completed?
