### ISSUE TITLE
convox ps sometimes shows cron job from other app

### ISSUE THREAD

**Issue by beedub** [convox/rack#744] opened 2016-06-08 18:11 UTC
```bash
$ convox ps
ID            NAME  RELEASE      SIZE  STARTED         COMMAND
d0f370524236  main  RPMIHYDDQAV  256   25 minutes ago  bash init.sh
e7f12a138315  main  RPMIHYDDQAV  256   24 minutes ago  bash init.sh
f042ce76d9fe  main  RPMIHYDDQAV  256   53 minutes ago  bash init.sh
$ convox ps
ID            NAME  RELEASE      SIZE  STARTED         COMMAND
81e3411f9c17  main  RLHLSDRHBMY  16    3 seconds ago   sh -c 'sync-cloudwatch --cluster=<CLUSTER> --env=prod'
d0f370524236  main  RPMIHYDDQAV  256   25 minutes ago  bash init.sh
e7f12a138315  main  RPMIHYDDQAV  256   24 minutes ago  bash init.sh
f042ce76d9fe  main  RPMIHYDDQAV  256   54 minutes ago  bash init.sh
$ convox ps
ID            NAME  RELEASE      SIZE  STARTED         COMMAND
d0f370524236  main  RPMIHYDDQAV  256   25 minutes ago  bash init.sh
e7f12a138315  main  RPMIHYDDQAV  256   24 minutes ago  bash init.sh
f042ce76d9fe  main  RPMIHYDDQAV  256   54 minutes ago  bash init.sh
[PENDING]     main  RRDSCKXIRXK  256
[PENDING]     main  RRDSCKXIRXK  256
[PENDING]     main  RRDSCKXIRXK  256
```

The task with release `RLHLSDRHBMY` in the second `convox ps` invocation is the one from another app

**Comment by nzoschke** [comment] 2016-06-15 21:16
Thanks for the report. This is a dupe of #494. Closing this in favor of the original report.

**Closed by nzoschke** 2016-06-15 21:16 UTC
