### ISSUE TITLE
Code Sync doesn't respect ENV variables

### ISSUE THREAD

**Issue by idris** [convox/rack#1388] opened 2016-11-11 20:03 UTC
In my Dockerfile, I have:
```
ENV APP_DIR=/usr/src/app
WORKDIR $APP_DIR
COPY . $APP_DIR/
```

When Convox syncs code (when running locally), the changed files get placed into `/usr/src/app/$APP_DIR` instead of `/usr/src/app`.  I guess Convox's code sync logic doesn't properly replace environment variables.

**Comment by soulshake** [comment] 2016-11-17 14:56
Thanks for the report.
Closing as duplicate of #1055

**Closed by soulshake** 2016-11-17 14:56 UTC
Labels: bug
