### ISSUE TITLE
Build caching

### ISSUE THREAD

**Issue by benjamin0** [convox/rack#267] opened 2016-01-19 22:23 UTC
Each time I `convox deploy`, the containers seem to be built from scratch without referencing the cache even though the first few commands haven't changed. Any ideas?

**Comment by nzoschke** [comment] 2016-02-09 01:52
Thank you for your report.

The intended behavior is to have fast builds due to caching of Docker images. So if you are seeing builds from scratch every time it is definitely a bug.

* When the API boots, it pulls the latest images for every app: https://github.com/convox/rack/blob/master/api/workers/images.go
* Builds happen on the same instance every time, so a second build should be fully cached and fast.

However I can think of a few things that might not be working here.

* The image pulling was split out into a single monitor task. It needs to move back to the API boot 
* Images are cleaned periodically if the disk is close to full utilization

**Comment by nzoschke** [comment] 2016-02-18 00:17
I tracked down these problems. https://github.com/convox/rack/issues/267 to track the fixes

**Comment by nzoschke** [comment] 2016-02-23 01:16
This was fixed in https://github.com/convox/rack/pull/357. After you update, the API will pull down the latest images for all your apps on boot, which means builds will have lots of cached layers to work against.

Thanks again for your report.

**Closed by nzoschke** 2016-02-23 01:16 UTC
